# Generated by Django 2.2.7 on 2022-06-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=100)),
                ('eventDescription', models.CharField(max_length=10000)),
                ('eventCoverImg', models.ImageField(blank=True, upload_to='eventImage')),
                ('eventRulebookLink', models.CharField(max_length=10000)),
                ('eventSociety', models.CharField(max_length=1000)),
                ('eventPocName', models.CharField(max_length=100)),
                ('eventPocContactNumber', models.IntegerField(default=None)),
                ('eventStartDate', models.DateTimeField(default=None)),
                ('eventEndDate', models.DateTimeField(default=None)),
                ('eventPrize', models.IntegerField(default=None)),
                ('eventPlatformLink', models.CharField(max_length=1000)),
            ],
        ),
    ]
