# Generated by Django 2.2.7 on 2022-06-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=1000)),
                ('userEmail', models.CharField(max_length=1000)),
                ('userContact', models.CharField(max_length=100)),
                ('userCollegeName', models.CharField(max_length=1000)),
                ('poetry', models.BooleanField(default=False)),
                ('article', models.BooleanField(default=False)),
                ('quiz', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
    ]
